server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms?useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 54yunkang
